# Use the same Java 25 version we specified in our workflow
FROM eclipse-temurin:25-jdk

# Create a volume for temporary files
VOLUME /tmp

# Copy the JAR file generated by Maven into the Docker image
COPY target/*.jar app.jar

# Specify the command to run when the container starts
ENTRYPOINT ["java","-jar","/app.jar"]