name: SWE304 CI/CD Pipeline

# This satisfies the requirement to trigger on push or pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # This satisfies the software version compliance requirement
      - name: Set up Java 26
        uses: actions/setup-java@v4
        with:
          java-version: '26'
          distribution: 'temurin'
          cache: maven

      - name: Make Maven Wrapper Executable
        run: chmod +x ./mvnw

      # This satisfies Task 2: Making the JAR on GitHub
      - name: Build JAR File with Maven
        run: ./mvnw clean package -DskipTests

      - name: Upload JAR Artifact (To verify it worked)
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar
          path: target/*.jar
          # This satisfies Task 3: Generate a docker image on GitHub
      - name: Build Docker Image
        run: docker build -t my-spring-app:latest .
        # This satisfies Task 4: Login to Dockerhub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # This satisfies Task 4: Push the image to Dockerhub
      - name: Tag and Push Docker Image
        run: |
          docker tag my-spring-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/swe304-project3:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/swe304-project3:latest
          # This satisfies Task 5: Transfer script and trigger compose.yml
      - name: Copy files via SCP (SFTP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "compose.yaml,deploy.sh"
          target: "/home/ubuntu/"

      - name: Execute Deployment Script via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x /home/ubuntu/deploy.sh
            /home/ubuntu/deploy.sh ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_TOKEN }}